CREATE DATETIME utanianca;
USE utanianca;

CREATE TABLE USUARIO(
COD_USUARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOMBRES_USUARIO VARCHAR(50) NOT NULL,
APELLIDOS_USUARIO VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
FOTO VARCHAR(100) NOT NULL,
USER_USUARIO VARCHAR(20) UNIQUE NOT NULL,
USER_CONTRASENA VARCHAR(1000) NOT NULL
);
 

CREATE TABLE ESTADO_DIARIO(
COD_ESTADO_DIARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOMBRES_USUARIO VARCHAR(50) NOT NULL
);

INSERT ESTADO_DIARIO(NOMBRES_USUARIO) VALUES('normal');
INSERT ESTADO_DIARIO(NOMBRES_USUARIO) VALUES('favorito');
INSERT ESTADO_DIARIO(NOMBRES_USUARIO) VALUES('archivado');



CREATE TABLE DIARIO(
COD_DIARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
COD_USUARIO INT NOT NULL, FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO),
COD_ESTADO_DIARIO INT NOT NULL, FOREIGN KEY (COD_ESTADO_DIARIO) REFERENCES ESTADO_DIARIO (COD_ESTADO_DIARIO),
TITULO VARCHAR(50) NOT NULL,
CONTENIDO TEXT NOT NULL,
FECHA_HORA DATETIME NOT NULL,
FOTO VARCHAR(100) NOT NULL
);






INSERT INTO USUARIO(NOMBRES_USUARIO, APELLIDOS_USUARIO, EMAIL, FOTO, USER_USUARIO, USER_CONTRASENA)
VALUES('Ivan','Sorio Solis','isoria@unajma.edu.pe','sin_foto_perfil.jpg','docente','$2y$10$KGC4LNMN/odWqkOC0v9sCugktWGJCJHC998Pk8SeQ853hwJ.PCCWm');





